SDK-6047: Final changes to plugin stub headers
neurala/via-native-plugins pull request #22
Opened 2021-12-09 16:51 UTC by liviuivan-neurala

**JIRA**: https://neurala.atlassian.net/browse/SDK-6047

Changelog
------------------

- marked both `VideoSource::frame` overloads `const`
- added `NEURALA_OS_LINUX` macro
- defined `ResultsOutputStatus`, `VideoSourceStatus`, `B4BError`, and `PluginStatus` as POD integer wrappers

Reviewer Checklist
------------------

> Should be edited by reviewers only

- [ ] Does this implement the story reqs?
- [ ] Does this match the [coding standard](../wiki/C-Based-Languages-Style-Guide)?
	- [ ] Are all TODO's in the [proper format](../wiki/C-Based-Languages-Style-Guide#commenting)?
	- [ ] Have JIRA tickets been made for all TODO's?
- [ ] Does this include tests that exercise the altered/added code?
- [ ] If it modifies a public API, is the documentation updated?

2021-12-09 18:44 UTC, liviuivan-neurala commented on stub/include/neurala/video/VideoSourceStatus.h
> +	static constexpr VideoSourceStatus unknown() { return {8}; }
I hesitate to change this to the value 2 (in line with the other enums) in case there are side effects. If we're sure it's safe, we could try it.

2021-12-09 19:08 UTC, jraynal requested changes

2021-12-09 19:08 UTC, jraynal commented on stub/include/neurala/error/B4BError.h
> +	int m_value;
Maybe we can make that `value` if we're going to use it directly.

2021-12-09 19:08 UTC, jraynal commented on stub/include/neurala/video/VideoSourceStatus.h
> +	static constexpr VideoSourceStatus unknown() { return {8}; }
Do it.

2021-12-09 19:08 UTC, jraynal commented on stub/include/neurala/video/VideoSourceStatus.h
> +struct VideoSourceStatus final
Any error code you think we should add here? I noticed you used the pixel format one and the overflow one not exactly the way it's intended in the C# plugin.

2021-12-13 18:12 UTC, Ziink4 reviewed
LGTM except for maybe https://github.com/neurala/B4B/pull/2927#discussion_r767982731

2021-12-16 12:03 UTC, Ziink4 approved these changes

2021-12-16 14:29 UTC, jraynal approved these changes

2021-12-20 17:32 UTC, merged