[SDK-6187] Synchronous .NET Plugin
neurala/via-native-plugins pull request #33
Opened 2022-04-19 15:24 UTC by Deneuki

Like https://github.com/neurala/via-native-plugins/pull/32 but synchronous.

2022-04-21 13:38 UTC, jraynal requested changes

2022-05-19 15:41 UTC, jraynal reviewed
I'd like to see a proper test in code.

2022-05-19 17:25 UTC, Deneuki commented
Does `Main.cpp` not count? If so, what would you like to see, instead?

2022-06-27 16:21 UTC, jraynal commented on plugins/csharp/Managed/VideoSource.cs
> +                Console.WriteLine($"THREAD {Thread.CurrentThread.ManagedThreadId} SENT IMAGE");
Can we do better for debug log? Less spammy, or at least more control as to the level of spamminess?

2026-06-05 12:20 UTC, closed without merging